# Site settings
title: Piscis Pulmenti Bankcorp
description: >
  Simple banking made easy
baseurl: # the subpath of your site, e.g. /blog/
# paginate: 10
url: "http://piscispulmenti.github.io"
# avatar: https://c1.staticflickr.com/5/4251/34999114475_94fe642e4b_m.jpg
# comments:
#   provider: disqus
#   disqus:
#     short_name: blancosilva

gems:
  - jekyll-sitemap

# Build settings
highlighter: rouge
markdown: kramdown

plugins: 
  - jekyll-seo-tag
